name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v4
    - name: Set up Python 3.11
      uses: actions/checkout@v5 #added
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
